### ISSUE TITLE
[Request] Update add-on for 1.18.x

### ISSUE THREAD

**Issue by knyghtmare** [konecnyjakub/Danse_Macabre#24]
Hello,

I have received a streaming request for this addon but I cannot find a release on the add-ons server for this (1.16/1.17). Thus, I am opening an issue ticker, hoping that you will be able to make the port.

Yours Sincerely,
LK

**Comment by konecnyjakub** [comment]
Hi, I am sorry for not responding sooner (and not porting this campaign in the first place). This campaign wasn't a priority for me in the last few years. Anyhow I should have some time to port it to Wesnoth 1.18 now (I will skip 1.16 as there is a newer stable version). I have pushed fixes for the most obvious issues to the master branch today and will try to play test the campaign as much as possible in the next few weeks/months.

**Comment by konecnyjakub** [comment]
Version 1.4.0 was just uploaded to Wesnoth 1.18.
