### ISSUE TITLE
Updates for Wesnoth 1.13

### ISSUE THREAD

**Issue by konecnyjakub** [konecnyjakub/Danse_Macabre#3]
I will use this to keep track of things that should be updated for Wesnoth 1.13 once I drop support for 1.12.

- [x] use macro ABILITY_LEADERSHIP instead of ABILITY_LEADERSHIP_LEVEL_X
- [x] add special note SPECIAL_NOTES_DEFENSE_CAP for cavalry units
- [x] use [message] image=none instead of magical comment for wmllint
- [x] remove {MAGENTA_IS_THE_TEAM_COLOR}, {SOUND:SLOW} and {SOUND:POISON}
- [x] undead_variation=wolf for the hound

**Comment by sevu** [comment]
- [ ] remove [portrait], use profile= instead for that. if the image in the wiki differs small_profile= can be used for that
- [ ]  mainline portrait location changed (wmllint in 1.13 updates that)
- [x] remove {MAGENTA_IS_THE_TEAM_COLOR}, {SOUND:SLOW} and {SOUND:POISON}. The engine does that now by itself.
- [ ] There are a lot of images which could be removed when removing support for older savefiles.
- [ ] undead_variation=wolf for the hound

**Comment by konecnyjakub** [comment]
Thanks for your comment. Well, I have removed [portrait] in 538c436f, which should also realise your second point (wmllint complained about special transparent portraits). Or did I miss anything? About {MAGENTA_IS_THE_TEAM_COLOR}, point taken, with the other macros I will look on it. Hm, which images can be removed?

**Comment by sevu** [comment]
You're welcome. I didn't knew wmllint complains about that. I listed it actually here because it because it's good to combine with the next point. Formerly, portrait used the images in portraits/transparent, while profile used them in portraits/. When removing [portrait] the locations are fitting again. However, wmllint does the job too.
For the images, see the WIP PR.
About the sound macros, zookeper explained it here:
https://gna.org/bugs/index.php?24853#comment1

**Comment by konecnyjakub** [comment]
Of course wmllint does that for you but I prefer making the suggested changes myself. About the sound macros, alright then.

**Comment by konecnyjakub** [comment]
Just noticed the undead_variation. Sounds good.

**Comment by konecnyjakub** [comment]
> Formerly, portrait used the images in portraits/transparent, while profile used them in portraits/.

That is what I was talking about here:
> wmllint complained about special transparent portraits

Sorry that I was not clear.

**Comment by sevu** [comment]
I just realized that this may require a bit more work, because we have no running wolf.

**Comment by konecnyjakub** [comment]
Oh, right. But still, it would be cool :) .

**Comment by sevu** [comment]
1.13 has new drake images. There's a mismatch between our lvl. 2,3,4 images and the lvl. 0,1 images from mainline, which we do use too. Like with the wolf, we need new recoloured sprites.
