### ISSUE TITLE
stderr

### ISSUE THREAD

**Issue by sevu** [konecnyjakub/Danse_Macabre#7]
This is what I got on stderr when i loaded Scenario 2 and jumped to the last one with debug mode.

> 20170226 14:15:24 error config: Multiple [unit_type]s with id=Running Spelk encountered.
20170226 14:15:24 warning engine/team_construction: warning: when building level, skipping a unit (id=[]) from leader_cfg with no type information,
for side:
allow_changes = no
allow_player = yes
chose_random = no
color = blue
controller = ai
current_player = 
faction_name = Custom
flag = flags/undead-flag-[1~4].png:150
flag_icon = flags/undead-flag-icon.png
fog = no
gold = 0
income = -2
is_local = yes
name = Macabre
no_leader = yes
player_id = Shiki
save_id = 15_dawn_of_the_dead_1
share_view = yes
shroud = no
side = 2
side_name = Macabre
team_name = macabre
user_team_name = Macabre
[ai]
        aggression = 0.8
        ai_algorithm = 
        caution = 0.1
        leader_value = 1
[/ai]
[ai]
        aggression = 0.8
        caution = 0.1
        leader_value = 1
[/ai]
[default_faction]
[/default_faction]
Invalid WML found: [set_recruit] missing required recruit= attribute

(the first line is eventually related to another add-on)

maybe the most is about a missing type= in a side definition in S15?

**Comment by konecnyjakub** [comment]
This one:
> Invalid WML found: [set_recruit] missing required recruit= attribute

is easy to fix.
About this:
> error config: Multiple [unit_type]s with id=Running Spelk encountered.

I am not so sure. Maybe you are using old save files?
The missing type= is weird because side 2 has no_leader=yes in its definition. Did this happen on Wesnoth 1.13?

**Comment by sevu** [comment]
was on 1.13.
The Running Spelk was twice in the compatibility file, easy to fix too.
About the type thing I don't know either...

**Comment by konecnyjakub** [comment]
> The Running Spelk was twice in the compatibility file, easy to fix too.

Oh, really. My bad.

**Comment by sevu** [comment]
Actually no problem at all.

**Comment by sevu** [comment]
Hmmm, same for S1
>20170226 19:41:46 warning engine/team_construction: warning: when building level, skipping a unit (id=[]) from leader_cfg with no type information,
for side:
allow_changes = no
chose_random = no
color = blue
controller = ai
current_player = 
faction_name = Custom
gold = 80
income = 8
is_local = yes
no_leader = yes
player_id = Shiki
recruit = Peasant,Ruffian,Woodsman
save_id = 01_beginning_of_the_tragedy_1
side = 2
team_name = humans
user_team_name = Human
[ai]
        aggression = 1
        ai_algorithm = 
        leader_value = 10
[/ai]
[ai]
        aggression = 1
        leader_value = 10
[/ai]
[village]
        x = 21
        y = 25
[/village]
[village]
        x = 12
        y = 25
[/village]
[village]
        x = 24
        y = 22
[/village]
[village]
        x = 20
        y = 22
[/village]
[village]
        x = 16
        y = 21
[/village]
[village]
        x = 11
        y = 22
[/village]
[village]
        x = 9
        y = 22
[/village]
[village]
        x = 16
        y = 19
[/village]
[default_faction]
        recruit = Peasant,Ruffian,Woodsman
[/default_faction]


Other thing from S2:
>20170226 19:43:43 warning ai/config: side 2: aspect with id=[recruitment_ignore_bad_combat] lacks default config facet!
20170226 19:43:43 warning ai/config: side 2: aspect with id=[recruitment_ignore_bad_movement] lacks default config facet!

and a bit later in S2
`20170226 19:46:36 error ai/engine/cpp: side 2 : UNKNOWN aspect[recruitment_ignore_bad_combat*composite_aspect]
20170226 19:46:36 error ai/engine/cpp: side 2 : UNKNOWN  aspect[recruitment_ignore_bad_movement*composite_aspect]`

This could be only related to mainline stuff though. Or maybe there was a change too.

**Comment by konecnyjakub** [comment]
Hmm, recruitment_ignore_bad_combat and recruitment_ignore_bad_movement do nothing at all in Wesnoth 1.12 and in 1.13.5 they were removed completely (according to wiki) so they can be removed from [side][ai].
About this:
> warning engine/team_construction: warning: when building level, skipping a unit (id=[]) from leader_cfg with no type information,

I just remembered wesnoth/wesnoth@95b2d8c4 . Not sure it that commit can fix that.

**Comment by sevu** [comment]
Do you have an idea what they were supposed to do?

I will try rebuilding prior to that commit.

**Comment by sevu** [comment]
That is it that commit

**Comment by konecnyjakub** [comment]
I managed to dig this up from wiki's history:
recruitment_ignore_bad_combat=no: (bool) If 'yes', the AI does not analyze the enemy units on the map to see if the unit to be recruited is suitable for fighting them. Affects recruitment CA only.
recruitment_ignore_bad_movement=no: (bool) if 'yes', the AI will not analyse the terrain to see if the unit is suitable for it.

**Comment by sevu** [comment]
I think we can just remove them.

**Comment by konecnyjakub** [comment]
Probably yes.

**Comment by sevu** [comment]
So, the issue with the long error message, it was actually a bug in mainline, thanks to you it has been found.
